### ISSUE TITLE
figure out how to deal with strings where there is no gps lock

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#110]
- some payloads appear to send 0,0,0 (lat, lon, alt) so the string parses but the point is clearly invalid and messes up the tracker
- some payloads send ,,, so the string does not parse
- curerntly spacenear.us prunes 0,0 points; the habitat web gui demo does this too (hacky addition)

@danielrichman 's suggestion:
- add a fix invalid key; doc[“data”][“fix_invalid”]. Payloads that send a fix valid field can be set from this and the points therefore ignored. Absence of key assumes valid fix.
- perhaps allow payloads to send either empty strings or a special character ‘!’ or something to set the fix_invalid field to false? This is a slight pain to implement.
- add a common post filter that detects if lat == lon == 0.0000 and sets fix_invalid = false, for use on payloads that do not do either of the above
- encourage people to do one of the two first options (or something else, better?)

**Comment by danielrichman** [comment]
[ukhas/habitat-transition 2179d92865fced52d0c478b8355fa8478dfabd65](https://github.com/ukhas/habitat-transition/commit/2179d92865fced52d0c478b8355fa8478dfabd65)

applied this quick hack today so that EURUS' telemetry with gps_lock = 0 wouldn't be shown on spacenearus. Went to make a note about it, and rediscovered this issue :-); the ideas here are far better.

One thing I thought of today was a possible 'gps_age' key in addition to alternatives 'fix_invalid' and 'gps_lock'; seconds since valid fix or -1 if none. Common filters could convert fix_invalid = !gps_lock or fix_invalid = gps_age > 15. (or w/e)

IIRC we also discussed, for payloads that send empty strings or ! or whatever (rather than lat = 0 lon = 0), two payload configuration docs per payload; one for the format it sends when it doesn't have a lock and one when it does, with the former setting fix_invalid.

</rambling>

**Comment by danielrichman** [comment]
Just looking over this again.

How about
- add the sensor base.constant, which expects the field to be exactly equal to the string in its config or it fails. Use this on people that send empty fields ,,, or garbage ,!!.!!!!!!,!!!.!!!!!!!, . Returns None;  note: views should test that lat/lon are floats and not None.
- add common filters:
  - invalid_location_zero: if lat==lon==0, fix_invalid.
  - invalid_gps_lock: data["fix_invalid"] = data["gps_lock"] not in config["ok_list"]
  - invalid_always: data["fix_invalid"] = True always.
- genpayload does the "for payloads that send empty strings or ! or whatever (rather than lat = 0 lon = 0), two payload configuration sentence items per payload; one for the format it sends when it doesn't have a lock and one when it does.

Don't need to do that now, but genpayload needs to know the names of those filters/how we choose to implement it. Relatively simple additions anyway.

**Comment by danielrichman** [comment]
PS: Currently base sensors are quite flexible, returning None if the string is empty. I suggest we make them more strict and then use the multiple-sentence configurations strategy if sometimes the payload sends empty fields.

**Comment by danielrichman** [comment]
Drafted the above features in https://github.com/danielrichman/habitat/compare/strict_parser

**Comment by danielrichman** [comment]
Closed by 5460517
