### ISSUE TITLE
support multiple transmission, sentence and radio settings for a payload

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#134]
parser will also have to support this

**Comment by danielrichman** [comment]
draft support for this has been added in places, by making the "transmission" "sentence" and "radio" keys of a payload object (in a flight doc) optionally arrays rather than objects; the array is a list of objects in the same format to try.
If this way of doing things is cool, then we can keep it and add support to the parser (dl-fldigi, habitat_extensions.transition currently use this to keep the RTTY/DOMEX multi mode stuff working.)

**Comment by adamgreig** [comment]
need to think about this in order to write the flight doc schema.

we could have each of transmission, sentence and radio be a list, with the same index referring to grouped stuff (so transmission[0] relates to sentence[0]) -- but then we can't have e.g. the same sentence transmitted at two baud rates.

we could have them be lists where indicies don't match up, but that might get.. very confusing as to what's actually going on

we could have each be an object, so transmission['fast'] and transmission['slow'] but sentence['data'], which also gives us names for free (for UI labels etc), but this might make life harder for the parser, the generator wizard's life harder and possibly be a pain to even come up with names for some things

we could have an object that contains each of these things, so like payloads["payload"]["fast"] = {"transmission": {}, "sentence": {}}, but then we have the same problem as in the first option.

we can have it be optional, but I think it'd be cleaner if all docs follow the same type here -- e.g. if we go for the list approach, we always have a list, but it often contains only one element.

**Comment by adamgreig** [comment]
related: the filters list, which might have to be a list of lists or similar? how do we determine what data should have which filters applied? should filters be a list inside each sentence object? do all filters apply to one specific sentence (I think so?)

**Comment by danielrichman** [comment]
Hmm. I think that tying a specific transmission obj to a sentence format obj is unnecessary, especially when one is used purely to autoconfigure dlfldigi and doesn't affect the parser. So instead how about transmission and sentence are lists; where the transmission can be any item in the list and the sentence can be any item in its list; i.e. they are unordered sets rather than lists. Is this what you meant by lists where the indices don't match? The autoconfigure i terface then allows you to select any one transmission obj from the list, and the parser tries each sentence obj in order until one matches. (we would have to make the parser slightly more strict on extra elements.

I agree that having a list with one item is better than sentence optionally being a single object or a list.

I also agree that filtera should move inside sentence{}. That makes more sense.

To justify the multi mode list thing, I guess ... well, there have only been a few examples of doing that. IIRC "ALPHA" had long sentences at 300baud and a short sentence at 50 with no sensors periodically. I believe someone else- though I forget who - transmits the same sentence on different bauds for fun. It's also SSDV would be two sentences for one transmission object. I think this accomodates all these in the easiest way possible.

**Comment by danielrichman** [comment]
note: habitat_extensions/cpp_uploader/src/UKHASExtractor.cxx may need updating when this issue is fixed.

**Comment by danielrichman** [comment]
Closed by 5460517
