### ISSUE TITLE
set up logrotate for habitat log text files

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#170]
we're keeping logging to files instead of moving logs to couch, but should set up log rotate to rotate them daily and compress and keep old logs.

**Comment by danielrichman** [comment]
Options
- Use WatchedFileHandler instead of FileHandler. This stat()s the logfile immediately before writing each line to check that the file hasn't been deleted/moved. Then a logrotate cronjob with compression, job done.
- Use RotatingFileHandler. Python does the rotating itself. Does not appear to support compression.

I like compression so I think the first option is better. Also is simpler.
Also, would need to setup wsgi log rotation separately, which would probably have to be logrotate + HUP. So I reckon having all of it handled by logrotate would be better.

Thoughts?

**Comment by danielrichman** [comment]
Done.

**Comment by danielrichman** [comment]
https://gist.github.com/3025813 for reference; all the stuff that keeps logrotate (and some other stuff) working.
