### ISSUE TITLE
write new genpayload

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#193]

**Comment by danielrichman** [comment]
genpayload features
- payload configuration doc creation
  
  features of strings that we want to handle:
  - no fix strings: zeros, !!!!, blank fields, whatever. Should parse.
  - multiple alternative strings
  - standard sensors, numeric scale and simple map filters.
  
  features (generally):
  - easy modification/copy of old docs (even for different payloads)
  - paste string, it fills out the boring bits (checksum, no. fields)
    and guesses the field types.
  - paste string, test it with the real parser (see below)
- flight doc creation
  
  should be super simple because this is the annoying thing you have to
  every flight
  
  select date range, launch location (lat,lng & name see schema).
  payloads config (from ones saved in database)
  
  ideally, have a "go to payload config maker" button at the last section
  if it's not too difficult to return to the flight doc editor afterwards.
- applicable to both: ownership of documents, logging in, etc.

musings on python parser tester daemon/service/api/thing
- flask app, imports habitat.parser. Need slight refactor of parser so that
  we can pass it stuff without touching the database, and get the parsed doc,
  logging messages, etc., without saving.
- for genpayload, need to be able to test a new document that the user is
  generating  i.e., not yet in the database.
  
  probably only need to consider payload configuration documents here.
- related #126: flask app for debugging parser
  which is in turn related to #131 manual telemetry upload
  
  different task: has to consider current state of database, including
  approved etc., flight docs in addition to payload configuration docs...
  
  probably a bad idea, in the name of keeping it simple.
  
  notes below are for later:
- if include #126, flask app needs to be able to test 'what would happen' if
  a string was uploaded right now + debug output.
  
  suggest: massively verbosify the parser, then change habitat log level
  to INFO. parser tester flask app can turn it down to debug and give the user
  the spam.

note: http://habitat.habhub.org/jse/

**Comment by danielrichman** [comment]
Reopening for transition milestone:

Need to minify, concat and gzip this so that it loads in a reasonable amount of time.

**Comment by danielrichman** [comment]
packing all the css and js into one file and minifying it appears to reduce load times by a negligible amount (approx 0.05s). By contrast, switching on gzip for cherokee reduces load times by a far more interesting 0.5s. The benefit from packing, minifying js, concatenating and minifying css is not worth the cpu cycles it takes to run uglifyjs.
